apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: 'gcr.io/favorable-iris-266409/database:v1'
        ports:
        - containerPort: 8080
        env: 
        - name: PROFILE
          value: cloud
