apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    name: database
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: database
  type: LoadBalancer
